apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: voting-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-database
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for SQL Server..."
              until nc -z database-service 1433; do
                echo "SQL Server is not ready yet..."
                sleep 5
              done
              echo "SQL Server is available!"

      containers:
        - name: backend
          image: votingsystem-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=database-service,1433;Database=VotingDB;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: voting-system
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP