name: CI Pipeline
on:
  push:
    branches:
      - jarifa2

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: |
        cd frontend
        npm install
        npm run build
  
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - run: |
          cd backend
          dotnet restore
          dotnet build

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build-frontend
      - build-backend
    steps:
      - uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run:  docker build -t cloudvote-frontend ./frontend

      - name: Build Backend Docker Image
        run:  docker build -t cloudvote-backend ./backend

    test-compose:
      runs-on: ubuntu-latest

      needs:
        - build-docker

      steps:
        - uses: actions/checkout@v4

        - name: Start Docker Compose
          run: docker compose up -d --build

        - name: Show Running Containers
          run: docker ps

        - name: Stop Containers
          if: always()
          run: docker compose down
